### ISSUE TITLE
autofocus

### ISSUE THREAD

**Issue by nagygabor** [Surbma/surbma-magyar-woocommerce#1]
Hello,

a megcserélt vezetéknév keresztnév-nél a keresztnéven marad az autofocus, így az oldal betöltésekor az lesz az aktív input a vezetéknév helyett.

<input class="input-text " name="billing_first_name" id="billing_first_name" placeholder="" value="" autocomplete="given-name" autofocus="autofocus" type="text">

köszi

**Comment by Surbma** [comment]
Köszi az észrevételt! Az autofocus levehető a keresztnévről, de nem adható hozzá a vezetéknévhez, de legalábbis egyelőre nem tudok erre megoldást.

A következő verzióban ezt javítom.

**Comment by Surbma** [comment]
Kész is. :)

**Comment by nagygabor** [comment]
Köszi, én sem bírtam ráadni az autofocust a vezetéknévre:(

**Comment by nagygabor** [comment]
Ez a megoldás:

// xnagyg
function surbma_mwc_filter_woocommerce_get_country_locale2( $locale ) {
    $locale['last_name']['autofocus'] = true;

    $locale['first_name']['autofocus'] = false;

    return $locale;
}
add_filter( 'woocommerce_default_address_fields', 'surbma_mwc_filter_woocommerce_get_country_locale2' );

**Comment by Surbma** [comment]
Ez szerintem nem megoldás. Nem veszi figyelembe, hogy Magyarország van-e kiválasztva az ország mezőben.

Illetve szerintem egyébként sem jó, mert a last_name-hez nem tartozik default autofocus attribútum, így nem is állítható true-ra. De az érték egyébként sem true, hanem autofocus.

Tesztelted ezt a kódot?

**Comment by nagygabor** [comment]
Teszteltem persze, működik, az lehet, hogy nem csak HU-ra.

a class-wc-countries.php 615-ös sorában van ez a tulajdonság definiálva true/false értékeket kell adni, az autofocus kimenetet ez alapján teszi ki a kód. (get_default_address_fields function)

Ezt a függényt a woocommerce_get_country_locale_default filter tudja módosítani, sajnos csak a locale['default'] értékbe. (Esetleg a kódban kellene valahogy megnézni, hogy HU van-e kiválasztva országnak és felételesen változtatni, de azt most nem tudom miként lehetne lekérdezni).

De még nézem

**Comment by nagygabor** [comment]
meg van a hiba oka! wc_array_overlay függvény hívás miatt van a probléma (nincs a lastname-nek autoficus tualjdonsága!

**Comment by nagygabor** [comment]
Ez a nyerő kód:

	// Custom checkout fields
	function surbma_mwc_filter_woocommerce_get_country_locale( $locale ) {
	    $locale['HU']['last_name']['priority'] = 10;
	    $locale['HU']['last_name']['class'] = array( 'form-row-first' );
	    $locale['HU']['last_name']['autofocus'] = true; //xnagyg
	
	    $locale['HU']['first_name']['priority'] = 20;
	    $locale['HU']['first_name']['class'] = array( 'form-row-last' );
	    $locale['HU']['first_name']['autofocus'] = false;
	
	    $locale['HU']['postcode']['priority'] = 42;
	    $locale['HU']['postcode']['class'] = array( 'form-row-first' );
	
	    $locale['HU']['city']['priority'] = 44;
	    $locale['HU']['city']['class'] = array( 'form-row-last' );
	
		if ( !defined( 'SURBMA_MWC_MEGYE' ) || SURBMA_MWC_MEGYE != true ) {
	    	$locale['HU']['state']['required'] = false;
		}
	
	    return $locale;
	}
	add_filter( 'woocommerce_get_country_locale', 'surbma_mwc_filter_woocommerce_get_country_locale' );
	
	// xnagyg: Change autofocus to last name
	function surbma_mwc_filter_woocommerce_default_address_fields( $locale ) {
	    $locale['last_name']['autofocus'] = false;
	    return $locale;
	}
	add_filter( 'woocommerce_default_address_fields', 'surbma_mwc_filter_woocommerce_default_address_fields');

**Comment by Surbma** [comment]
Az autofocus beállításával én is próbálkoztam, de a last_name mezőnek ugye nincs ilyen attribútuma. Nem értem, hogy ez a plusz filter miért kell, illetve, hogy miért működik emiatt, de tényleg működik. :)
