### ISSUE TITLE
Számlázz.hu vezetéknév-keresztnév csere

### ISSUE THREAD

**Issue by nagygabor** [Surbma/surbma-magyar-woocommerce#2]
Hello,

ha gondolod bele lehet építeni a számlázz.hu javítást is, hogy ne felcserélve jelenjen meg a számlán a név. 

Ez a kód hozzá:

//Vezetéknév-keresztnév csere
add_filter('wc_szamlazz_xml','xnagyg_wc_szamlazz_xml_name_order',10,2);

function xnagyg_wc_szamlazz_xml_name_order($xml,$order) {
  //Név csere
  $xml->vevo->nev = ( strlen($order->billing_company)>0 ? htmlspecialchars($order->billing_company, ENT_XML1, 'UTF-8') : $order->billing_last_name.' '.$order->billing_first_name);
  
  //Szállítási név csere
  if ( strlen($xml->vevo->postazasiNev) > 0 ) {
	$xml->vevo->postazasiNev = ( strlen($order->shipping_company)>0 ? htmlspecialchars($order->shipping_last_name, ENT_XML1, 'UTF-8') : $order->billing_last_name.' '.$order->shipping_first_name);
  }

  return $xml;
}

**Comment by Surbma** [comment]
Igazából nem szeretem az ilyen megoldásokat. Ezt a számlázz.hu fejlesztőknek kéne megírni, hogy a last name legyen a vezetéknév és a first name a keresztnév, mert ez a hivatalos és így használják a legtöbben.

Tudom, hogy van, aki az egyedi fordítással oldotta meg és felcserélte a vezetéknevet és a keresztnevet, de ez nem a jó megoldás és én semmiképpen sem szeretném támogatni, hogy így maradjon.

Szóval nekik kell megírni, hogy ez a bővítmény rendbeteszi a nevek sorrendjét, ezért mindenki a helyes módon tudja használni a neveket, így nekik kell cserélniük ezt a bővítményükben.

**Comment by nagygabor** [comment]
"Ezt a számlázz.hu fejlesztőknek kéne megírni, hogy a last name legyen a vezetéknév és a first name a keresztnév, mert ez a hivatalos és így használják a legtöbben."

Megértem az álláspontodat, ezt jobb lenne a szamlazz.hu pluginben megoldani (hivatalos nincs is), de azt nem nagyon fejlesztik. Egyébként nem a hivatalos sorrendet használják a legtöbben, pont fordítva.

"Tudom, hogy van, aki az egyedi fordítással oldotta meg és felcserélte a vezetéknevet és a keresztnevet, de ez nem a jó megoldás és én semmiképpen sem szeretném támogatni, hogy így maradjon."

Ezzel egyébként pont a helytelen megoldást támogatod, mert így erre a pluginre nem fognak átállni, mert nem "kompatibilis" a magyar pluginekkel (akik a nem helyes sorrendet tekintik "elfogadottnak" - ez most a magyar de facto megoldás /fordítással való megoldás/)

"Szóval nekik kell megírni, hogy ez a bővítmény rendbeteszi a nevek sorrendjét, ezért mindenki a helyes módon tudja használni a neveket, így nekik kell cserélniük ezt a bővítményükben." Igen, az lenne a megoldás ha minden magyar pluginben lenne lehetőség a sorrend meghatározásához. (Meg is fogom csinálni a szamlazz.hu-hoz, de kérdés hogy beteszi-e a fejlesztő). "Ha mohamed nem megy a hegyhez..."

De persze ez a te döntésed.

(Emlékszem amikor a Microsoft kiadta a win 95-öt és több ezer program - a fejlesztők hibájából - nem volt vele kompatibilis, akkor a Microsoft oprendszer szinten kezelte ezt a több ezer programot, hogy kompatibilis legyen, csak hogy a userek váltsanak. Szerintem ez az út minden szereplőnek jobb, mint elvi alpavetően helyes álláspontokhoz ragaszkodni)

**Comment by Surbma** [comment]
Ez az egyetlen célja, küldetése a bővítménynek, hogy rendbetegye a WooCommerce bővítményt a magyar felhasználóknak. Szóval azok fogják választani és használni, akik jól akarják használni, mindenféle gagyi és nem ideális "megoldások" helyett.

Szóval ez az egyetlen esély, hogy a többiek is ehhez igazodjanak. Ennek tükrében ők tűnnek a gagyi, amatőr megoldásnak.

Minden felhasználót arra kell bíztatni, hogy írjon a fejlesztőknek, hogy javítsák a kódot.
